# ============================================================
# MediScan — Expanded Medicine Database (100+ entries)
# Sourced from standard pharmacological references
# ============================================================

EXTENDED_MEDS = [
    # ---- PAIN / FEVER ----
    {"name":"Diclofenac","strength":"50mg","brands":["Voveran","Voltaren","Cataflam"],"category":"NSAID Anti-inflammatory","safety":"caution","uses":"Relieves pain and inflammation in arthritis, sprains, menstrual pain, migraines, and post-operative pain.","dosage":"50mg 2-3 times daily with food. Maximum 150mg/day.","sideEffects":"Stomach upset, nausea, dizziness, headache. Increased risk of cardiovascular events with long-term use.","warnings":"Take with food. Avoid if you have heart disease, stomach ulcers, or kidney problems. Not for use in late pregnancy.","keywords":["diclofenac","voveran","voltaren","cataflam","diclo"]},
    {"name":"Naproxen","strength":"250mg","brands":["Aleve","Naprosyn","Naxdom"],"category":"NSAID Anti-inflammatory","safety":"caution","uses":"Treats pain, inflammation, and fever. Used for arthritis, gout, menstrual cramps, tendinitis, bursitis.","dosage":"250-500mg twice daily with food. Maximum 1250mg first day, then 1000mg/day.","sideEffects":"Stomach pain, heartburn, drowsiness, headache. Risk of GI bleeding with prolonged use.","warnings":"Take with food or milk. Avoid with aspirin allergy. Not recommended in 3rd trimester of pregnancy.","keywords":["naproxen","aleve","naprosyn","naxdom"]},
    {"name":"Tramadol","strength":"50mg","brands":["Ultram","Tramazac","Contramal"],"category":"Opioid Analgesic","safety":"danger","uses":"Treats moderate to severe pain. Used post-surgery, in chronic pain conditions, and cancer pain management.","dosage":"50-100mg every 4-6 hours as needed. Maximum 400mg/day. As prescribed by doctor only.","sideEffects":"Dizziness, nausea, constipation, drowsiness, headache. Risk of dependence and seizures.","warnings":"PRESCRIPTION ONLY. Habit-forming — risk of addiction. Do NOT combine with alcohol or sedatives. May cause seizures. Not for children under 12.","keywords":["tramadol","ultram","tramazac","contramal"]},
    {"name":"Mefenamic Acid","strength":"500mg","brands":["Ponstan","Meftal","Ponstel"],"category":"NSAID Analgesic","safety":"caution","uses":"Treats menstrual pain (dysmenorrhea), mild to moderate pain, headache, dental pain, and musculoskeletal pain.","dosage":"500mg three times daily with food. Use for shortest duration possible.","sideEffects":"Stomach upset, diarrhea, nausea, dizziness. May worsen asthma in sensitive individuals.","warnings":"Take with food. Avoid if allergic to aspirin or NSAIDs. Not for long-term use. Avoid in late pregnancy.","keywords":["mefenamic","ponstan","meftal","ponstel","mefacid"]},
    {"name":"Aceclofenac","strength":"100mg","brands":["Hifenac","Zerodol","Aceclo"],"category":"NSAID Anti-inflammatory","safety":"caution","uses":"Relieves pain and inflammation in osteoarthritis, rheumatoid arthritis, ankylosing spondylitis, and dental pain.","dosage":"100mg twice daily with food.","sideEffects":"Stomach pain, diarrhea, nausea, dizziness. Less GI side effects than diclofenac.","warnings":"Take with food. Avoid in severe liver/kidney disease. Not for use in late pregnancy.","keywords":["aceclofenac","hifenac","zerodol","aceclo"]},

    # ---- ANTIBIOTICS ----
    {"name":"Ciprofloxacin","strength":"500mg","brands":["Cipro","Ciplox","Cifran"],"category":"Antibiotic (Fluoroquinolone)","safety":"caution","uses":"Treats urinary tract infections, respiratory infections, bone and joint infections, skin infections, and gastroenteritis.","dosage":"250-750mg twice daily for 7-14 days depending on infection.","sideEffects":"Nausea, diarrhea, dizziness, headache. Risk of tendon damage (especially Achilles tendon) and peripheral neuropathy.","warnings":"PRESCRIPTION ONLY. Avoid in pregnancy and children under 18. May cause tendon rupture — stop if tendon pain occurs. Increases sun sensitivity. Avoid dairy products within 2 hours.","keywords":["ciprofloxacin","cipro","ciplox","cifran","ciproflo"]},
    {"name":"Cephalexin","strength":"500mg","brands":["Keflex","Sporidex","Ceff"],"category":"Antibiotic (Cephalosporin)","safety":"caution","uses":"Treats skin infections, respiratory tract infections, urinary tract infections, bone infections, and ear infections.","dosage":"250-500mg every 6 hours for 7-14 days. Complete the full course.","sideEffects":"Diarrhea, nausea, stomach upset, vaginal yeast infection. Rare: allergic reaction.","warnings":"PRESCRIPTION ONLY. Inform doctor of penicillin allergy (cross-reactivity possible). Complete full course.","keywords":["cephalexin","keflex","sporidex","ceff","cepha"]},
    {"name":"Doxycycline","strength":"100mg","brands":["Vibramycin","Doxt","Doxyl"],"category":"Antibiotic (Tetracycline)","safety":"caution","uses":"Treats acne, respiratory infections, urinary infections, malaria prevention, Lyme disease, and sexually transmitted infections.","dosage":"100mg twice daily on day 1, then 100mg once daily. Take with plenty of water.","sideEffects":"Nausea, sun sensitivity, esophageal irritation, vaginal yeast infection.","warnings":"PRESCRIPTION ONLY. Do NOT take with dairy or antacids. Avoid sun exposure. Do NOT use in pregnancy or children under 8 (stains teeth). Take with full glass of water, remain upright 30 min after.","keywords":["doxycycline","vibramycin","doxt","doxyl","doxy"]},
    {"name":"Metronidazole","strength":"400mg","brands":["Flagyl","Metrogyl","Aristogyl"],"category":"Antibiotic / Antiprotozoal","safety":"caution","uses":"Treats anaerobic bacterial infections, dental infections, H. pylori, amoebiasis, giardiasis, trichomoniasis, and surgical prophylaxis.","dosage":"400mg three times daily for 5-7 days. Take with or after food.","sideEffects":"Nausea, metallic taste, dark urine, headache, dizziness.","warnings":"PRESCRIPTION ONLY. Absolutely NO ALCOHOL during treatment and 48 hours after — causes severe nausea and vomiting (disulfiram-like reaction).","keywords":["metronidazole","flagyl","metrogyl","aristogyl","metro"]},
    {"name":"Levofloxacin","strength":"500mg","brands":["Levaquin","Levoflox","Tavanic"],"category":"Antibiotic (Fluoroquinolone)","safety":"caution","uses":"Treats pneumonia, sinusitis, urinary tract infections, skin infections, and chronic bronchitis.","dosage":"500-750mg once daily for 5-14 days depending on infection type.","sideEffects":"Nausea, diarrhea, dizziness, insomnia. Risk of tendon damage and nerve problems.","warnings":"PRESCRIPTION ONLY. Same tendon and nerve risks as ciprofloxacin. Avoid in pregnancy. Increases sun sensitivity.","keywords":["levofloxacin","levaquin","levoflox","tavanic","levo"]},
    {"name":"Clindamycin","strength":"300mg","brands":["Cleocin","Dalacin","Clindac"],"category":"Antibiotic (Lincosamide)","safety":"caution","uses":"Treats serious skin and soft tissue infections, bone infections, dental infections, and pelvic infections. Alternative for penicillin-allergic patients.","dosage":"150-450mg every 6 hours. Take with full glass of water.","sideEffects":"Diarrhea (can be severe — C. diff), nausea, skin rash, abdominal pain.","warnings":"PRESCRIPTION ONLY. Stop immediately and contact doctor if severe diarrhea occurs (risk of C. difficile colitis).","keywords":["clindamycin","cleocin","dalacin","clindac","clinda"]},

    # ---- DIABETES ----
    {"name":"Glimepiride","strength":"2mg","brands":["Amaryl","Glimisave","Glimy"],"category":"Antidiabetic (Sulfonylurea)","safety":"caution","uses":"Controls blood sugar in Type 2 diabetes by stimulating insulin release from the pancreas.","dosage":"1-4mg once daily with breakfast. Start low, titrate slowly as directed by doctor.","sideEffects":"Hypoglycemia (low blood sugar), weight gain, nausea, dizziness.","warnings":"PRESCRIPTION ONLY. Risk of hypoglycemia — always carry sugar. Take with food. Monitor blood sugar regularly.","keywords":["glimepiride","amaryl","glimisave","glimy","glim"]},
    {"name":"Sitagliptin","strength":"100mg","brands":["Januvia","Istavel","Zita"],"category":"Antidiabetic (DPP-4 Inhibitor)","safety":"caution","uses":"Controls blood sugar in Type 2 diabetes. Can be used alone or with metformin. Lower risk of hypoglycemia than sulfonylureas.","dosage":"100mg once daily with or without food.","sideEffects":"Upper respiratory infection, headache, nausea. Rare: pancreatitis, joint pain.","warnings":"PRESCRIPTION ONLY. Report severe abdominal pain immediately (possible pancreatitis). Dose adjustment needed in kidney disease.","keywords":["sitagliptin","januvia","istavel","zita","sitag"]},
    {"name":"Insulin Glargine","strength":"100 IU/mL","brands":["Lantus","Basaglar","Toujeo"],"category":"Long-acting Insulin","safety":"danger","uses":"Controls blood sugar in Type 1 and Type 2 diabetes. Provides basal insulin coverage for 24 hours.","dosage":"Individualized dose, injected subcutaneously once daily at the same time. As directed by endocrinologist.","sideEffects":"Hypoglycemia, injection site reactions, weight gain, lipodystrophy.","warnings":"PRESCRIPTION ONLY. Store in refrigerator. Never shake. Risk of severe hypoglycemia. Always carry glucose tablets. Never share insulin pens.","keywords":["insulin","glargine","lantus","basaglar","toujeo"]},

    # ---- CARDIOVASCULAR ----
    {"name":"Amlodipine","strength":"5mg","brands":["Norvasc","Amlong","Amlip"],"category":"Calcium Channel Blocker","safety":"caution","uses":"Treats high blood pressure (hypertension) and angina (chest pain). Relaxes blood vessels to improve blood flow.","dosage":"5-10mg once daily. May take 1-2 weeks for full effect.","sideEffects":"Ankle swelling (edema), flushing, headache, dizziness, fatigue.","warnings":"PRESCRIPTION ONLY. Do not stop suddenly. Avoid grapefruit juice. Monitor blood pressure regularly. Report severe swelling.","keywords":["amlodipine","norvasc","amlong","amlip","amlod"]},
    {"name":"Losartan","strength":"50mg","brands":["Cozaar","Losar","Losacar"],"category":"ARB Antihypertensive","safety":"caution","uses":"Treats hypertension, diabetic kidney disease, and heart failure. Protects kidneys in diabetic patients.","dosage":"50mg once daily. May increase to 100mg/day. Take at the same time each day.","sideEffects":"Dizziness, hyperkalemia (high potassium), fatigue, nasal congestion.","warnings":"PRESCRIPTION ONLY. NOT for use in pregnancy (can harm fetus). Monitor potassium levels. May cause dizziness on standing.","keywords":["losartan","cozaar","losar","losacar","losar"]},
    {"name":"Telmisartan","strength":"40mg","brands":["Micardis","Telma","Telsartan"],"category":"ARB Antihypertensive","safety":"caution","uses":"Treats high blood pressure and reduces cardiovascular risk. Longest-acting ARB with 24-hour coverage.","dosage":"20-80mg once daily. Usually 40mg as starting dose.","sideEffects":"Dizziness, back pain, diarrhea, upper respiratory infection.","warnings":"PRESCRIPTION ONLY. NOT for use in pregnancy. Monitor kidney function and potassium.","keywords":["telmisartan","micardis","telma","telsartan","telmi"]},
    {"name":"Metoprolol","strength":"50mg","brands":["Lopressor","Betaloc","Metolar"],"category":"Beta-Blocker","safety":"caution","uses":"Treats hypertension, angina, heart failure, and prevents heart attacks. Controls heart rate in atrial fibrillation.","dosage":"25-100mg twice daily. Extended release: 25-200mg once daily.","sideEffects":"Fatigue, cold hands/feet, dizziness, slow heartbeat, weight gain.","warnings":"PRESCRIPTION ONLY. Do NOT stop suddenly (risk of rebound hypertension/heart attack). May mask symptoms of low blood sugar in diabetics.","keywords":["metoprolol","lopressor","betaloc","metolar","meto"]},
    {"name":"Ramipril","strength":"5mg","brands":["Altace","Cardace","Ramipres"],"category":"ACE Inhibitor","safety":"caution","uses":"Treats hypertension, heart failure, and protects kidneys. Reduces risk of heart attack and stroke.","dosage":"2.5-10mg once daily. Start low and titrate up.","sideEffects":"Dry cough (persistent), dizziness, headache, fatigue. Rare: angioedema (facial swelling).","warnings":"PRESCRIPTION ONLY. NOT for use in pregnancy. Stop immediately if facial/tongue swelling occurs (angioedema). Monitor kidney function.","keywords":["ramipril","altace","cardace","ramipres","rami"]},
    {"name":"Clopidogrel","strength":"75mg","brands":["Plavix","Clopilet","Deplatt"],"category":"Antiplatelet","safety":"danger","uses":"Prevents blood clots after heart attack, stroke, or stent placement. Often used with aspirin (dual antiplatelet therapy).","dosage":"75mg once daily. With or without food.","sideEffects":"Bleeding, bruising, stomach upset, diarrhea, rash.","warnings":"PRESCRIPTION ONLY. Significantly increases bleeding risk. Inform all doctors/dentists. Do NOT stop before surgery without consulting cardiologist.","keywords":["clopidogrel","plavix","clopilet","deplatt","clopi"]},
    {"name":"Warfarin","strength":"5mg","brands":["Coumadin","Warf","Acitrom"],"category":"Anticoagulant","safety":"danger","uses":"Prevents and treats blood clots (DVT, PE). Used in atrial fibrillation, mechanical heart valves, and post-stroke.","dosage":"Individualized based on INR blood test. Usually 2-10mg daily. Regular blood monitoring required.","sideEffects":"Bleeding (major risk), bruising, nausea, hair loss.","warnings":"PRESCRIPTION ONLY. Requires regular INR monitoring. Many drug and food interactions (vitamin K foods). Absolutely NOT in pregnancy. Report any unusual bleeding immediately.","keywords":["warfarin","coumadin","warf","acitrom"]},

    # ---- RESPIRATORY ----
    {"name":"Salbutamol","strength":"100mcg/puff","brands":["Ventolin","Asthalin","ProAir"],"category":"Bronchodilator (Beta-2 Agonist)","safety":"safe","uses":"Quick relief of asthma symptoms, bronchospasm, and COPD. Opens airways within minutes during an asthma attack.","dosage":"1-2 puffs every 4-6 hours as needed. Shake well before use. Use spacer if available.","sideEffects":"Tremor, increased heart rate, headache, nervousness, palpitations.","warnings":"If needing rescue inhaler more than 3 times/week, your asthma is not well controlled — see doctor. Do not exceed 8 puffs/day. Seek emergency help if symptoms don't improve.","keywords":["salbutamol","ventolin","asthalin","proair","albuterol","inhaler"]},
    {"name":"Montelukast","strength":"10mg","brands":["Singulair","Montair","MonteLK"],"category":"Leukotriene Receptor Antagonist","safety":"safe","uses":"Prevents asthma attacks and exercise-induced bronchospasm. Also relieves seasonal allergic rhinitis (hay fever).","dosage":"10mg once daily in the evening. Children 6-14 years: 5mg chewable tablet.","sideEffects":"Headache, stomach pain, fatigue. Rare: mood changes, vivid dreams, irritability.","warnings":"Not for acute asthma attacks — use rescue inhaler for that. Report any mood or behavioral changes immediately. Take in the evening for best results.","keywords":["montelukast","singulair","montair","montelk","monte"]},
    {"name":"Budesonide","strength":"200mcg/puff","brands":["Pulmicort","Budecort","Foracort"],"category":"Inhaled Corticosteroid","safety":"safe","uses":"Prevents and controls asthma symptoms. Long-term controller medication that reduces airway inflammation.","dosage":"200-400mcg twice daily via inhaler. Rinse mouth after each use to prevent thrush.","sideEffects":"Oral thrush (candidiasis), hoarseness, sore throat. Minimal systemic effects at recommended doses.","warnings":"Not for acute attacks. Always rinse mouth after inhalation. Do not stop suddenly if on long-term therapy — taper under medical supervision.","keywords":["budesonide","pulmicort","budecort","foracort","budes"]},

    # ---- GASTROINTESTINAL ----
    {"name":"Ranitidine","strength":"150mg","brands":["Zantac","Rantac","Aciloc"],"category":"H2-Receptor Antagonist","safety":"danger","uses":"Treats and prevents stomach ulcers, acid reflux (GERD), and heartburn. Reduces stomach acid production.","dosage":"150mg twice daily or 300mg at bedtime. For heartburn prevention: 150mg 30-60 min before triggering food.","sideEffects":"Headache, dizziness, constipation, diarrhea. Generally well tolerated.","warnings":"Note: Some brands were recalled due to NDMA contamination — use alternatives if concerned. Not for long-term unsupervised use.","keywords":["ranitidine","zantac","rantac","aciloc","ranit"]},
    {"name":"Domperidone","strength":"10mg","brands":["Motilium","Domstal","Vomistop"],"category":"Antiemetic / Prokinetic","safety":"safe","uses":"Treats nausea, vomiting, and bloating. Improves stomach emptying. Used in gastroparesis and with certain medications that cause nausea.","dosage":"10mg three times daily, 15-30 minutes before meals. Maximum 30mg/day.","sideEffects":"Dry mouth, headache, abdominal cramps. Rare: changes in heart rhythm.","warnings":"Use lowest effective dose for shortest time. Avoid in severe liver impairment. Not recommended with certain heart rhythm medications.","keywords":["domperidone","motilium","domstal","vomistop","domper"]},
    {"name":"Ondansetron","strength":"4mg","brands":["Zofran","Emeset","Vomikind"],"category":"Antiemetic (5-HT3 Antagonist)","safety":"safe","uses":"Prevents nausea and vomiting caused by chemotherapy, radiation therapy, surgery, and pregnancy (severe cases).","dosage":"4-8mg every 8 hours as needed. Can be taken orally or dissolved on tongue.","sideEffects":"Headache, constipation, dizziness, fatigue.","warnings":"May cause QT prolongation — use caution in heart disease. Inform doctor of all medications. Adjust dose in liver impairment.","keywords":["ondansetron","zofran","emeset","vomikind","ondans"]},
    {"name":"Loperamide","strength":"2mg","brands":["Imodium","Lopamide","Eldoper"],"category":"Antidiarrheal","safety":"safe","uses":"Treats acute diarrhea and chronic diarrhea. Slows gut motility to reduce frequency of stools.","dosage":"4mg initially, then 2mg after each loose stool. Maximum 16mg/day. Use for shortest time needed.","sideEffects":"Constipation, stomach cramps, nausea, dizziness, dry mouth.","warnings":"Do NOT use in bloody diarrhea or bacterial dysentery. Not for children under 2. Stop if constipation occurs. Drink plenty of fluids.","keywords":["loperamide","imodium","lopamide","eldoper","loper"]},
    {"name":"Lactulose","strength":"10g/15mL","brands":["Duphalac","Laxose","Crelax"],"category":"Osmotic Laxative","safety":"safe","uses":"Treats constipation and hepatic encephalopathy. Softens stool by drawing water into the bowel.","dosage":"15-30mL once daily for constipation. May take 24-48 hours to work. Adjust dose for soft stool.","sideEffects":"Bloating, flatulence, abdominal cramps, nausea. Usually improves after a few days.","warnings":"May take a few days to show effect — do not increase dose impatiently. Safe in pregnancy. Monitor electrolytes with long-term use in elderly.","keywords":["lactulose","duphalac","laxose","crelax","lactu"]},

    # ---- ANTIDEPRESSANT / MENTAL HEALTH ----
    {"name":"Sertraline","strength":"50mg","brands":["Zoloft","Serlift","Daxid"],"category":"SSRI Antidepressant","safety":"caution","uses":"Treats depression, anxiety disorders, OCD, PTSD, panic disorder, and social anxiety. First-line treatment with proven safety profile.","dosage":"50mg once daily. May increase to 200mg/day over several weeks as directed by psychiatrist.","sideEffects":"Nausea, diarrhea, insomnia, dizziness, sexual dysfunction, drowsiness.","warnings":"PRESCRIPTION ONLY. May take 2-4 weeks to show effect. Do NOT stop suddenly (withdrawal symptoms). Monitor for worsening depression or suicidal thoughts in young adults. Avoid alcohol.","keywords":["sertraline","zoloft","serlift","daxid","sert"]},
    {"name":"Escitalopram","strength":"10mg","brands":["Lexapro","Cipralex","Nexito"],"category":"SSRI Antidepressant","safety":"caution","uses":"Treats major depressive disorder and generalized anxiety disorder. Most selective SSRI with fewest drug interactions.","dosage":"10mg once daily. May increase to 20mg/day after 1 week. Take in morning or evening.","sideEffects":"Nausea, headache, insomnia, drowsiness, sexual dysfunction.","warnings":"PRESCRIPTION ONLY. Takes 2-4 weeks for full effect. Do NOT stop abruptly. Do NOT combine with MAOIs. Monitor mood changes.","keywords":["escitalopram","lexapro","cipralex","nexito","escit"]},
    {"name":"Alprazolam","strength":"0.5mg","brands":["Xanax","Alprax","Restyl"],"category":"Benzodiazepine (Anxiolytic)","safety":"danger","uses":"Short-term treatment of anxiety disorders and panic disorder. Provides rapid relief of acute anxiety symptoms.","dosage":"0.25-0.5mg three times daily. Use lowest effective dose for shortest time. As prescribed by psychiatrist only.","sideEffects":"Drowsiness, dizziness, memory impairment, dependence, fatigue, coordination problems.","warnings":"PRESCRIPTION ONLY. HIGH ADDICTION POTENTIAL. Do NOT combine with alcohol or opioids (risk of death). Do NOT stop suddenly (seizure risk). Short-term use only. Impairs driving.","keywords":["alprazolam","xanax","alprax","restyl","alpraz"]},

    # ---- THYROID ----
    {"name":"Levothyroxine","strength":"50mcg","brands":["Synthroid","Thyronorm","Eltroxin"],"category":"Thyroid Hormone","safety":"caution","uses":"Replaces thyroid hormone in hypothyroidism (underactive thyroid). Also used in thyroid cancer management and goiter.","dosage":"25-200mcg once daily on empty stomach, 30-60 minutes before breakfast. Dose based on TSH levels.","sideEffects":"Usually none at correct dose. Overdose symptoms: palpitations, tremor, weight loss, insomnia, sweating.","warnings":"PRESCRIPTION ONLY. Take on empty stomach with water only. Separate from calcium, iron, and antacids by 4 hours. Regular TSH monitoring required. Do not switch brands without doctor approval.","keywords":["levothyroxine","synthroid","thyronorm","eltroxin","thyroxine","levo"]},

    # ---- VITAMINS / SUPPLEMENTS ----
    {"name":"Vitamin D3","strength":"60000 IU","brands":["Calcirol","D-Rise","Arachitol"],"category":"Vitamin Supplement","safety":"safe","uses":"Treats and prevents vitamin D deficiency. Supports calcium absorption, bone health, immunity, and muscle function.","dosage":"60000 IU once weekly for 8 weeks (loading), then monthly maintenance. Or as per blood levels.","sideEffects":"Generally safe at recommended doses. Excess: nausea, constipation, weakness, kidney stones.","warnings":"Get vitamin D levels tested before starting high doses. Do not exceed prescribed amount. Take with fatty meal for best absorption.","keywords":["vitamin d","vitamind3","calcirol","drise","arachitol","d3","cholecalciferol"]},
    {"name":"Vitamin B12","strength":"1500mcg","brands":["Methylcobalamin","Mecobalamin","Nurokind"],"category":"Vitamin Supplement","safety":"safe","uses":"Treats B12 deficiency, peripheral neuropathy, pernicious anemia. Supports nerve function and red blood cell formation.","dosage":"1500mcg once daily or as directed. Sublingual or oral forms available.","sideEffects":"Generally very safe. Rare: mild diarrhea, itching.","warnings":"Vegetarians and vegans are at higher risk of deficiency. Get levels checked. Injectable forms available for severe deficiency.","keywords":["vitamin b12","b12","methylcobalamin","mecobalamin","nurokind","cobalamin"]},
    {"name":"Iron + Folic Acid","strength":"100mg + 500mcg","brands":["Autrin","Orofer","Dexorange"],"category":"Hematologic Supplement","safety":"safe","uses":"Treats and prevents iron deficiency anemia. Essential during pregnancy to prevent neural tube defects and anemia.","dosage":"One tablet daily with vitamin C (orange juice) for better absorption. Take on empty stomach if tolerated.","sideEffects":"Constipation, dark stools, nausea, stomach upset. Take with food if stomach upset occurs.","warnings":"Keep away from children (iron overdose is dangerous in kids). Do not take with milk, tea, or coffee (reduces absorption). Separate from calcium and antacids by 2 hours.","keywords":["iron","folic acid","autrin","orofer","dexorange","ferrous"]},
    {"name":"Calcium + Vitamin D","strength":"500mg + 250IU","brands":["Shelcal","Calcimax","Gemcal"],"category":"Bone Health Supplement","safety":"safe","uses":"Prevents and treats calcium deficiency and osteoporosis. Essential for bone strength, especially in post-menopausal women.","dosage":"One tablet twice daily after meals. Best absorbed when taken with food.","sideEffects":"Constipation, bloating, gas. Rare: kidney stones with excessive use.","warnings":"Do not exceed recommended dose. Separate from iron, thyroid medications by 4 hours. Adequate water intake important.","keywords":["calcium","shelcal","calcimax","gemcal","calcium d3"]},
    {"name":"Multivitamin","strength":"Multi","brands":["Supradyn","Becosules","Zincovit"],"category":"Nutritional Supplement","safety":"safe","uses":"Supplements daily vitamin and mineral requirements. Supports general health, immunity, energy, and recovery.","dosage":"One tablet daily with food. Do not exceed one tablet per day.","sideEffects":"Nausea on empty stomach, bright yellow urine (riboflavin), mild stomach upset.","warnings":"Not a substitute for balanced diet. Take with food. May interact with certain medications — inform your doctor.","keywords":["multivitamin","supradyn","becosules","zincovit","vitamin"]},
    {"name":"Omega-3 Fatty Acids","strength":"1000mg","brands":["Maxepa","Mega-3","Evion LC"],"category":"Lipid Supplement","safety":"safe","uses":"Supports heart health, reduces triglycerides, anti-inflammatory. May benefit brain and joint health.","dosage":"1-2 capsules daily with meals.","sideEffects":"Fishy aftertaste, burping, mild GI upset. Store in refrigerator to reduce.","warnings":"May increase bleeding risk in high doses. Inform doctor if taking blood thinners. Choose mercury-tested brands.","keywords":["omega3","omega 3","fish oil","maxepa","epa","dha"]},

    # ---- ANTI-ALLERGY / DERMATOLOGY ----
    {"name":"Fexofenadine","strength":"120mg","brands":["Allegra","Fexova","Histafree"],"category":"Antihistamine (Non-sedating)","safety":"safe","uses":"Treats seasonal allergies, chronic urticaria (hives), and allergic rhinitis without causing drowsiness.","dosage":"120mg once daily or 180mg once daily for urticaria. Take with water.","sideEffects":"Headache, nausea, dizziness. Truly non-drowsy in most people.","warnings":"Avoid taking with fruit juices (reduces absorption). Juice-free window of 4 hours before and 1 hour after.","keywords":["fexofenadine","allegra","fexova","histafree","fexo"]},
    {"name":"Levocetirizine","strength":"5mg","brands":["Xyzal","Levocet","Vozet"],"category":"Antihistamine","safety":"safe","uses":"Treats allergic rhinitis, chronic urticaria, and other allergic conditions. Active isomer of cetirizine — effective at half the dose.","dosage":"5mg once daily in the evening. Children 6-12: 2.5mg daily.","sideEffects":"Mild drowsiness, dry mouth, fatigue. Less sedating than first-generation antihistamines.","warnings":"May cause drowsiness — caution with driving. Dose reduction in kidney impairment.","keywords":["levocetirizine","xyzal","levocet","vozet","levocet"]},
    {"name":"Hydroxyzine","strength":"25mg","brands":["Atarax","Ucerax"],"category":"Antihistamine (Sedating)","safety":"caution","uses":"Treats anxiety, severe itching (pruritus), urticaria, and insomnia. Has sedative and anti-anxiety effects.","dosage":"25mg 2-3 times daily. For sleep: 25-50mg at bedtime.","sideEffects":"Significant drowsiness, dry mouth, dizziness, blurred vision.","warnings":"Causes drowsiness — do NOT drive. Avoid alcohol. Use lowest effective dose in elderly (fall risk). Not for long-term anxiety management.","keywords":["hydroxyzine","atarax","ucerax","hydroxy"]},
    {"name":"Fluconazole","strength":"150mg","brands":["Diflucan","Forcan","Flucos"],"category":"Antifungal","safety":"caution","uses":"Treats yeast infections (vaginal candidiasis, oral thrush), fungal skin infections, and systemic fungal infections.","dosage":"150mg single dose for vaginal candidiasis. 50-400mg daily for other infections as prescribed.","sideEffects":"Headache, nausea, stomach pain, diarrhea, rash.","warnings":"PRESCRIPTION ONLY. Multiple drug interactions — inform doctor of all medications. Liver function monitoring for prolonged use. Avoid in pregnancy.","keywords":["fluconazole","diflucan","forcan","flucos","fluco"]},
    {"name":"Clotrimazole","strength":"1% cream","brands":["Canesten","Candid","Clotrim"],"category":"Topical Antifungal","safety":"safe","uses":"Treats fungal skin infections including athlete's foot, ringworm, jock itch, and vaginal yeast infections (cream/pessary).","dosage":"Apply thin layer to affected area 2-3 times daily for 2-4 weeks. Continue 1 week after symptoms resolve.","sideEffects":"Mild burning, stinging, redness at application site. Generally very well tolerated.","warnings":"For external use only. Do not apply to eyes. Complete full course even if symptoms improve early. Consult doctor if no improvement in 4 weeks.","keywords":["clotrimazole","canesten","candid","clotrim","clotri"]},

    # ---- CORTICOSTEROIDS ----
    {"name":"Prednisolone","strength":"10mg","brands":["Wysolone","Omnacortil","Deltacortril"],"category":"Corticosteroid","safety":"caution","uses":"Treats severe allergies, asthma exacerbations, autoimmune diseases, inflammatory conditions, and organ transplant rejection.","dosage":"Varies widely: 5-60mg daily depending on condition. Taper gradually — never stop suddenly.","sideEffects":"Weight gain, mood changes, insomnia, increased blood sugar, fluid retention, osteoporosis with long-term use.","warnings":"PRESCRIPTION ONLY. NEVER stop abruptly after long-term use (adrenal crisis). Increases infection risk. Causes blood sugar spikes in diabetics. Carry steroid card.","keywords":["prednisolone","wysolone","omnacortil","deltacortril","pred","steroid"]},

    # ---- ANTI-ANXIETY / SLEEP ----
    {"name":"Zolpidem","strength":"10mg","brands":["Ambien","Zolfresh","Stilnoct"],"category":"Sedative-Hypnotic","safety":"danger","uses":"Short-term treatment of insomnia (difficulty falling asleep). Works within 15-30 minutes.","dosage":"10mg at bedtime (5mg in elderly/women). Use for maximum 2-4 weeks. Take immediately before bed.","sideEffects":"Next-day drowsiness, dizziness, headache, complex sleep behaviors (sleep-walking, sleep-driving).","warnings":"PRESCRIPTION ONLY. High abuse potential. Take only if you can stay in bed 7-8 hours. Do NOT take with alcohol. May cause bizarre behavior during sleep. Short-term use only.","keywords":["zolpidem","ambien","zolfresh","stilnoct","zolp"]},

    # ---- MIGRAINE ----
    {"name":"Sumatriptan","strength":"50mg","brands":["Imitrex","Suminat","Imigran"],"category":"Triptan (Migraine)","safety":"caution","uses":"Treats acute migraine attacks with or without aura. Also treats cluster headaches. Does not prevent migraines.","dosage":"50-100mg at onset of migraine. May repeat after 2 hours if partial response. Maximum 200mg/day.","sideEffects":"Chest tightness/pressure, tingling, dizziness, drowsiness, flushing.","warnings":"PRESCRIPTION ONLY. Not for prevention — only acute attacks. Not for hemiplegic or basilar migraine. Avoid if you have heart disease or uncontrolled hypertension.","keywords":["sumatriptan","imitrex","suminat","imigran","suma"]},

    # ---- ANTI-EPILEPTIC ----
    {"name":"Gabapentin","strength":"300mg","brands":["Neurontin","Gabapin","Gabantin"],"category":"Anticonvulsant / Nerve Pain","safety":"caution","uses":"Treats epilepsy (partial seizures), neuropathic pain (diabetic neuropathy, post-herpetic neuralgia), and restless legs syndrome.","dosage":"300mg on day 1, 300mg twice daily on day 2, 300mg three times daily on day 3. Titrate up as needed. Max 3600mg/day.","sideEffects":"Drowsiness, dizziness, fatigue, weight gain, peripheral edema.","warnings":"PRESCRIPTION ONLY. Do not stop suddenly (seizure risk). Dose adjustment in kidney disease. May impair driving. Abuse potential.","keywords":["gabapentin","neurontin","gabapin","gabantin","gaba"]},

    # ---- MUSCLE RELAXANT ----
    {"name":"Cyclobenzaprine","strength":"10mg","brands":["Flexeril","Relaxyl"],"category":"Muscle Relaxant","safety":"caution","uses":"Short-term relief of muscle spasm associated with acute musculoskeletal conditions like back pain and neck pain.","dosage":"5-10mg three times daily. Use for 2-3 weeks maximum. Take with or without food.","sideEffects":"Drowsiness, dry mouth, dizziness, fatigue, blurred vision.","warnings":"Not for long-term use. Causes significant drowsiness — avoid driving. Do not use with MAOIs. Avoid alcohol.","keywords":["cyclobenzaprine","flexeril","relaxyl","cyclo"]},

    # ---- UROLOGY ----
    {"name":"Tamsulosin","strength":"0.4mg","brands":["Flomax","Urimax","Contiflo"],"category":"Alpha-1 Blocker","safety":"caution","uses":"Treats benign prostatic hyperplasia (BPH / enlarged prostate). Relaxes prostate and bladder neck muscles to improve urination.","dosage":"0.4mg once daily, 30 minutes after the same meal each day.","sideEffects":"Dizziness, runny nose, abnormal ejaculation, drowsiness.","warnings":"PRESCRIPTION ONLY. Rise slowly from sitting/lying (orthostatic hypotension). Inform ophthalmologist before cataract surgery (floppy iris syndrome).","keywords":["tamsulosin","flomax","urimax","contiflo","tamsu"]},

    # ---- ANTI-GOUT ----
    {"name":"Allopurinol","strength":"100mg","brands":["Zyloric","Allopur","Zurig"],"category":"Xanthine Oxidase Inhibitor","safety":"caution","uses":"Prevents gout attacks by lowering uric acid levels. Also prevents uric acid kidney stones.","dosage":"100-300mg once daily after meals. Start low (100mg) to avoid triggering gout flare.","sideEffects":"Skin rash (stop immediately if occurs), nausea, diarrhea, drowsiness.","warnings":"PRESCRIPTION ONLY. Drink plenty of fluids. Stop immediately if skin rash develops (risk of severe hypersensitivity — SJS/TEN). May initially worsen gout — use with colchicine cover.","keywords":["allopurinol","zyloric","allopur","zurig","allo"]},

    # ---- EMERGENCY / ORS ----
    {"name":"ORS (Oral Rehydration Salts)","strength":"Standard WHO","brands":["Electral","ORS Powder","Pedialyte"],"category":"Rehydration Therapy","safety":"safe","uses":"Treats and prevents dehydration from diarrhea, vomiting, excessive sweating, and heat exhaustion. WHO-recommended formula.","dosage":"Dissolve one sachet in 1 liter of clean drinking water. Sip frequently. For children: small sips every 1-2 minutes.","sideEffects":"Generally none. Mild nausea if consumed too quickly.","warnings":"Use clean water only. Do not add sugar or salt. Discard after 24 hours. Seek medical help if dehydration persists or bloody diarrhea present.","keywords":["ors","oral rehydration","electral","pedialyte","rehydration","electrolyte"]},

    # ---- CONTRACEPTION ----
    {"name":"Levonorgestrel","strength":"1.5mg","brands":["Plan B","iPill","Unwanted 72"],"category":"Emergency Contraceptive","safety":"caution","uses":"Emergency contraception — prevents pregnancy after unprotected sex or contraceptive failure. Effective within 72 hours.","dosage":"1.5mg single tablet as soon as possible, ideally within 12 hours. Effective up to 72 hours after unprotected intercourse.","sideEffects":"Nausea, vomiting, menstrual irregularity, breast tenderness, fatigue, headache.","warnings":"NOT a regular contraceptive — for emergencies only. Less effective in women over 70kg. Does NOT protect against STIs. If vomiting within 2 hours, take another dose. See doctor if period is delayed by more than 7 days.","keywords":["levonorgestrel","plan b","ipill","unwanted 72","emergency","morning after"]},
]

# Known drug interactions (bidirectional)
# Each key is a frozenset of two generic medicine names (lowercased)
DRUG_INTERACTIONS = {
    frozenset(["aspirin", "ibuprofen"]): "Aspirin + Ibuprofen: Ibuprofen may reduce the cardioprotective effect of aspirin. Increased risk of GI bleeding. Consult doctor.",
    frozenset(["aspirin", "warfarin"]): "Aspirin + Warfarin: HIGH RISK — significantly increased bleeding risk. Requires close medical supervision and INR monitoring.",
    frozenset(["aspirin", "clopidogrel"]): "Aspirin + Clopidogrel: Dual antiplatelet therapy — increased bleeding risk. Only use under cardiologist supervision.",
    frozenset(["ibuprofen", "naproxen"]): "Ibuprofen + Naproxen: Do NOT combine two NSAIDs — doubles the risk of stomach bleeding and kidney damage.",
    frozenset(["ibuprofen", "aspirin"]): "Ibuprofen + Aspirin: Ibuprofen can block aspirin's heart-protective effect. Take aspirin 30 min before ibuprofen if both are needed.",
    frozenset(["warfarin", "metronidazole"]): "Warfarin + Metronidazole: Metronidazole significantly increases warfarin's blood-thinning effect. HIGH BLEEDING RISK.",
    frozenset(["warfarin", "ciprofloxacin"]): "Warfarin + Ciprofloxacin: Ciprofloxacin increases warfarin levels. Monitor INR closely.",
    frozenset(["metformin", "ciprofloxacin"]): "Metformin + Ciprofloxacin: May cause dangerous blood sugar fluctuations (both hypo- and hyperglycemia).",
    frozenset(["sertraline", "tramadol"]): "Sertraline + Tramadol: HIGH RISK of serotonin syndrome (confusion, rapid heartbeat, high temperature). Avoid combination.",
    frozenset(["escitalopram", "tramadol"]): "Escitalopram + Tramadol: Risk of serotonin syndrome. Avoid this combination.",
    frozenset(["alprazolam", "zolpidem"]): "Alprazolam + Zolpidem: DANGEROUS — excessive sedation, respiratory depression, risk of death. Never combine.",
    frozenset(["alprazolam", "tramadol"]): "Alprazolam + Tramadol: DANGEROUS — risk of severe respiratory depression and death. FDA black box warning.",
    frozenset(["metformin", "insulin glargine"]): "Metformin + Insulin: Increased risk of hypoglycemia. Monitor blood sugar closely. Dose adjustments may be needed.",
    frozenset(["amlodipine", "metoprolol"]): "Amlodipine + Metoprolol: May cause excessive blood pressure drop and very slow heart rate. Use under medical supervision.",
    frozenset(["omeprazole", "clopidogrel"]): "Omeprazole + Clopidogrel: Omeprazole reduces clopidogrel's effectiveness. Use pantoprazole instead if PPI needed.",
    frozenset(["levothyroxine", "calcium + vitamin d"]): "Levothyroxine + Calcium: Calcium reduces thyroid hormone absorption. Take thyroid medication 4 hours before calcium.",
    frozenset(["levothyroxine", "iron + folic acid"]): "Levothyroxine + Iron: Iron reduces thyroid hormone absorption. Separate by at least 4 hours.",
    frozenset(["ciprofloxacin", "iron + folic acid"]): "Ciprofloxacin + Iron: Iron drastically reduces ciprofloxacin absorption. Separate by 2 hours.",
    frozenset(["doxycycline", "calcium + vitamin d"]): "Doxycycline + Calcium: Calcium chelates doxycycline, making the antibiotic ineffective. Separate by 2-3 hours.",
    frozenset(["prednisolone", "ibuprofen"]): "Prednisolone + Ibuprofen: Greatly increased risk of stomach ulcers and GI bleeding. Use gastroprotection (PPI) if both needed.",
}
